### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by joefiorini** [frapontillo/angular-filters#6]
NPM has improved its support for browser dependencies over the past year. My team is now looking into migrating from bower to NPM. I notice you already have a `package.json`, would you mind publishing releases to NPM?

**Comment by frapontillo** [comment]
Any particular metadata I should take care of?

**Comment by joefiorini** [comment]
Nah, I think your `package.json` looks pretty good as is. Thanks!

**Comment by frapontillo** [comment]
NPM package has been published: https://www.npmjs.com/package/angular-filters

Sorry for the delay.
